                                         ---CREATING MATERIAL WITHDRAWN TABLE---
                                            --MATERIAL WITHDRAW HEADER--

CREATE TABLE T_TMW_HDR
( TMW_NO VARCHAR2(20) CONSTRAINT tmwh_PO_pk PRIMARY KEY,
 TMW_DATE DATE Default sysdate,
TMW_PROJ_CODE CONSTRAINT tmwh_proj_code NOT NULL references PROJECT(P_CODE),
TMW_APPROVED_BY VARCHAR2 (100) CONSTRAINT twh_approved_by_nn NOT NULL,
TMW_APPROVED_DATE DATE CONSTRAINT twh_approved_date NOT NULL,
TMW_ENT_BY VARCHAR2(30) DEFAULT USER,
TMW_ENT_DATE DATE DEFAULT SYSDATE,
TMW_UPDATE_BY VARCHAR2 (30) DEFAULT USER,
TMW_UPDATE_DATE DATE DEFAULT SYSDATE);
 

SELECT * FROM T_TMW_HDR;


INSERT INTO T_TMW_HDR
( TMW_NO ,
TMW_PROJ_CODE ,
TMW_APPROVED_BY ,
TMW_APPROVED_DATE )
VALUES
('&TMW_NO','&PROJ_CODE','&APR_BY',&DATE);
