                                             --MATERIAL WITHDRAW DETAIL--

CREATE TABLE T_TMW_DTL
( TMW_PO_NO VARCHAR2 (20) CONSTRAINT tmwd_po_no_fk REFERENCES T_TMW_HDR(TMW_NO),
TMW_DATE DATE DEFAULT SYSDATE,
TMW_ITEM_CODE VARCHAR2 (30) CONSTRAINT tmwd_po_itemcode_nn NOT NULL references ITEM(I_CODE),
TMW_PO_UNIT VARCHAR2(10) CONSTRAINT tmwd_po_unit_nn NOT NULL,
TMW_UNIT_PRICE NUMBER(16,2)  CONSTRAINT tmwd_po_unit_proce_nn NOT NULL,
TMW_ENT_BY VARCHAR2 (30)  DEFAULT USER,
TMW_ENT_DATE DATE DEFAULT SYSDATE,
TMW_UPDATE_BY VARCHAR2 (30) DEFAULT USER,
TMW_UPDATE_DATE DATE DEFAULT SYSDATE);
 
