SELECT TMWD.TMW_PO_NO,TMWD.TMW_ITEM_CODE,I.I_NAME,TMWH.TMW_PROJ_CODE,P.P_NAME,TMWH.TMW_NO
FROM  T_TMW_DTL  TMWD,ITEM I , T_TMW_HDR  TMWH, PROJECT P
WHERE TMWD.TMW_PO_NO=TMWH.TMW_NO
AND TMWD.TMW_ITEM_CODE=I.I_CODE
AND TMW_PROJ_CODE=P.P_CODE;
AND TPOD.TPD_po_no= T_PO_HDR.TPH_po_no;



                         ---Displaying Result According to the Condition---

SELECT EMPLOYEE_ID,FIRST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES  WHERE FIRST_NAME='Adam');
